spring:
  application:
    name: auth-service

  # postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/hustgo_auth_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Redis
  redis:
    host: redis
    port: 6379

# JWT
jwt:
  secret: 1fff1f8da50efdae56c62665986370b0e5b9fb9e605982d5eef26613effa39e5
  expiration: 604800000

server:
  port: 8080

app:
  google:
    client-id: 749124689963-5i72ctaou6jbeb2panc897oohduhfi0h.apps.googleusercontent.com