server:
  port: 8082
spring:
  application:
    name: hub-service

  # postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/hustgo_hub_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Kafka Producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

services:
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8080}

# topic name
app:
  kafka:
    topics:
      hub-events: hub-events

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
