server {
    listen 80;
    server_name _; # Tên miền(IP / Domain)

    root /usr/share/nginx/html;
    index index.html;

    # Chống cache cho các file cấu hình và HTML
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    # Cho phép cache 1 năm với các file tĩnh (JS, CSS, img)
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
