export const HANOI_DISTRICTS = [
  { value: "BA_DINH", label: "Quận Ba Đình" },
  { value: "HOAN_KIEM", label: "Quận Hoàn Kiếm" },
  { value: "TAY_HO", label: "Quận Tây Hồ" },
  { value: "CAU_GIAY", label: "Quận Cầu Giấy" },
  { value: "DONG_DA", label: "Quận Đống Đa" },
  { value: "HAI_BA_TRUNG", label: "Quận Hai Bà Trưng" },
  { value: "HOANG_MAI", label: "Quận Hoàng Mai" },
  { value: "THANH_XUAN", label: "Quận Thanh Xuân" },
  { value: "LONG_BIEN", label: "Quận Long Biên" },
  { value: "NAM_TU_LIEM", label: "Quận Nam Từ Liêm" },
  { value: "BAC_TU_LIEM", label: "Quận Bắc Từ Liêm" },
  { value: "HA_DONG", label: "Quận Hà Đông" },

  { value: "BA_VI", label: "Huyện Ba Vì" },
  { value: "CHUONG_MY", label: "Huyện Chương Mỹ" },
  { value: "DAN_PHUONG", label: "Huyện Đan Phượng" },
  { value: "DONG_ANH", label: "Huyện Đông Anh" },
  { value: "GIA_LAM", label: "Huyện Gia Lâm" },
  { value: "HOAI_DUC", label: "Huyện Hoài Đức" },
  { value: "ME_LINH", label: "Huyện Mê Linh" },
  { value: "MY_DUC", label: "Huyện Mỹ Đức" },
  { value: "PHU_XUYEN", label: "Huyện Phú Xuyên" },
  { value: "PHUC_THO", label: "Huyện Phúc Thọ" },
  { value: "QUOC_OAI", label: "Huyện Quốc Oai" },
  { value: "SOC_SON", label: "Huyện Sóc Sơn" },
  { value: "THACH_THAT", label: "Huyện Thạch Thất" },
  { value: "THANH_OAI", label: "Huyện Thanh Oai" },
  { value: "THANH_TRI", label: "Huyện Thanh Trì" },
  { value: "THUONG_TIN", label: "Huyện Thường Tín" },
  { value: "UNG_HOA", label: "Huyện Ứng Hòa" },
  { value: "SON_TAY", label: "Thị xã Sơn Tây" },
];
