spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                allowedMethods:
                  - OPTIONS
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                allowedHeaders:
                  - "*"
                allowCredentials: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - name: AuthenticationFilter

            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/api/hubs/**, /api/internal/hubs/**
              filters:
                - name: AuthenticationFilter

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**
              filters:
                - RewritePath=/api/payments/(?<segment>.*), /api/payments/${segment}

server:
  port: 9191

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# JWT
jwt:
  secret: ${JWT_SECRET}
  expiration: 604800000