name: SonarCloud Analysis

on:
  push:
    branches:
      - prod
      - main
  pull_request:
    branches:
      - prod
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # SonarCloud cần clone toàn bộ lịch sử git để phân tích độ thay đổi code
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build and analyze with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Tự động có sẵn trong GitHub Actions
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Cần khai báo trong Settings GitHub
        run: |
          cd backend
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests -Dsonar.projectKey=nghnam04_HustGo-Platform -Dsonar.organization=nghnam04
